# Generated by Django 5.1.6 on 2026-01-20 10:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cargos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cargo", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Faltas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=3)),
                ("descricao", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="FiltroSalvo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                (
                    "efetivo",
                    models.CharField(
                        choices=[("ambos", "Ambos"), ("sim", "Sim"), ("nao", "Não")],
                        max_length=10,
                    ),
                ),
                (
                    "ativo",
                    models.CharField(
                        choices=[("ambos", "Ambos"), ("sim", "Sim"), ("nao", "Não")],
                        max_length=10,
                    ),
                ),
                ("cargos", models.ManyToManyField(blank=True, to="rh.cargos")),
                ("faltas", models.ManyToManyField(blank=True, to="rh.faltas")),
            ],
        ),
        migrations.CreateModel(
            name="Pessoas",
            fields=[
                (
                    "id",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("nome", models.CharField(max_length=150)),
                ("dt_nasc", models.DateField(default="1991-01-01")),
                ("cpf", models.CharField(default="11111111111", max_length=11)),
                ("admissao", models.DateField(default="1991-01-01")),
                ("saida", models.DateField(null=True)),
                (
                    "efetivo",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")], default=False
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")], default=True
                    ),
                ),
                (
                    "func_publico",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Sim"), (False, "Não")],
                        default=True,
                    ),
                ),
                (
                    "cargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pessoas_cargos",
                        to="rh.cargos",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Faltas_Pessoas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(default=django.utils.timezone.now)),
                ("qtd_dias", models.IntegerField(default=1)),
                (
                    "falta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rh.faltas"
                    ),
                ),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rh.pessoas"
                    ),
                ),
            ],
            options={
                "unique_together": {("pessoa", "data")},
            },
        ),
        migrations.CreateModel(
            name="Pontuacoes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano", models.IntegerField()),
                ("funcao", models.IntegerField()),
                ("cargo", models.IntegerField()),
                ("ue", models.IntegerField()),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rh.pessoas"
                    ),
                ),
            ],
            options={
                "unique_together": {("ano", "pessoa")},
            },
        ),
    ]
