# Generated by Django 5.1.6 on 2026-01-22 15:57

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cargos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cargo", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Faltas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=3)),
                ("descricao", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Pessoas",
            fields=[
                (
                    "id",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("nome", models.CharField(max_length=150)),
                ("dt_nasc", models.DateField(default=datetime.date(1991, 1, 1))),
                ("cpf", models.CharField(default="11111111111", max_length=11)),
                ("admissao", models.DateField(default=datetime.date(1991, 1, 1))),
                ("saida", models.DateField(blank=True, null=True)),
                (
                    "efetivo",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")], default=False
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")], default=True
                    ),
                ),
                (
                    "func_publico",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Sim"), (False, "Não")],
                        default=True,
                    ),
                ),
                (
                    "cargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pessoas_cargos",
                        to="rh.cargos",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pontuacoes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano", models.IntegerField()),
                ("funcao", models.IntegerField()),
                ("cargo", models.IntegerField()),
                ("ue", models.IntegerField()),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rh.pessoas"
                    ),
                ),
            ],
            options={
                "unique_together": {("ano", "pessoa")},
            },
        ),
        migrations.CreateModel(
            name="RegistroFalta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(default=django.utils.timezone.now)),
                ("qtd_dias", models.IntegerField(default=1)),
                (
                    "falta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rh.faltas"
                    ),
                ),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rh.pessoas"
                    ),
                ),
            ],
            options={
                "db_table": "rh_faltas_pessoas",
                "unique_together": {("pessoa", "data")},
            },
        ),
    ]
