# Generated by Django 5.1.6 on 2026-01-20 13:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroFalta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(default=django.utils.timezone.now)),
                ("qtd_dias", models.IntegerField(default=1)),
                (
                    "falta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rh.faltas"
                    ),
                ),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rh.pessoas"
                    ),
                ),
            ],
            options={
                "db_table": "faltas_pessoas",
                "unique_together": {("pessoa", "data")},
            },
        ),
    ]
