# Generated by Django 5.1.6 on 2026-01-21 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0002_registrofalta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filtrosalvo",
            name="cargos",
        ),
        migrations.RemoveField(
            model_name="filtrosalvo",
            name="faltas",
        ),
        migrations.AlterField(
            model_name="pessoas",
            name="admissao",
            field=models.DateField(default=datetime.date(1991, 1, 1)),
        ),
        migrations.AlterField(
            model_name="pessoas",
            name="dt_nasc",
            field=models.DateField(default=datetime.date(1991, 1, 1)),
        ),
        migrations.AlterModelTable(
            name="registrofalta",
            table="rh_faltas_pessoas",
        ),
        migrations.DeleteModel(
            name="Faltas_Pessoas",
        ),
        migrations.DeleteModel(
            name="FiltroSalvo",
        ),
    ]
