# Generated by Django 4.1.3 on 2022-12-09 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_cargo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('dt_nasc', models.DateField(default='1991-01-01')),
                ('cpf', models.CharField(default='11111111111', max_length=11)),
                ('admissao', models.DateField(default='1991-01-01')),
                ('efetivo', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoas_cargos', to='app_cargo.cargos')),
            ],
        ),
    ]
