# Generated by Django 4.1.3 on 2022-12-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pessoa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoas',
            name='saida',
            field=models.DateField(default=None),
        ),
    ]
