# Generated by Django 5.1.6 on 2026-01-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_pessoa", "0009_pessoas_func_publico"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pessoas",
            name="func_publico",
            field=models.BooleanField(
                blank=True, choices=[(True, "Sim"), (False, "Não")], default=True
            ),
        ),
    ]
