# Generated by Django 4.2.3 on 2024-10-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telefone_fixo_publico', models.CharField(max_length=11)),
                ('endereco', models.CharField(max_length=200)),
            ],
        ),
    ]
