# Generated by Django 4.2.3 on 2025-02-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appInstituicao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='instituicao',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
