# Generated by Django 4.2.3 on 2024-03-05 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appAluno', '0024_delete_matricula'),
        ('appClasse', '0002_alter_classe_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(default=0)),
                ('numero', models.IntegerField(default=0)),
                ('situacao', models.CharField(choices=[('C', 'CURSANDO'), ('BXTR', 'TRANSFERIDO'), ('REMA', 'REMANEJADO'), ('NCFP', 'Ñ COMP. FORA PRAZO'), ('P', 'PROMOVIDO'), ('R', 'REPROVADO')], default='A', max_length=4)),
                ('data_matricula', models.DateField(null=True)),
                ('data_movimentacao', models.DateField(null=True)),
                ('aluno', models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='appAluno.aluno')),
                ('classe', models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='appClasse.classe')),
            ],
            options={
                'unique_together': {('ano', 'aluno', 'situacao', 'data_matricula')},
            },
        ),
    ]
