# Generated by Django 4.2.3 on 2024-03-06 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAluno', '0024_delete_matricula'),
        ('appMatricula', '0002_alter_matricula_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together={('id', 'ano', 'aluno', 'situacao', 'data_matricula')},
        ),
    ]
