# Generated by Django 4.2.3 on 2024-10-06 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAno', '0001_initial'),
        ('appMatricula', '0004_alter_matricula_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='ano',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='appAno.ano'),
        ),
    ]
