# Generated by Django 4.2.3 on 2024-03-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appClasse', '0002_alter_classe_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='ano',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='classe',
            name='periodo',
            field=models.CharField(choices=[('M', 'MANHÃ'), ('T', 'TARDE')], max_length=1),
        ),
        migrations.AlterField(
            model_name='classe',
            name='serie',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='classe',
            name='turma',
            field=models.CharField(max_length=1),
        ),
    ]
