# Generated by Django 4.1.3 on 2022-11-08 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ficha_cem', '0002_alter_faltas_tipo_pontuacoes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='faltas_pessoas',
            unique_together={('pessoa', 'data')},
        ),
    ]
