# Generated by Django 4.1.3 on 2022-11-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ficha_cem', '0007_pontuacoesatribuicoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoas',
            name='id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
