# Generated by Django 4.1.3 on 2022-11-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ficha_cem', '0008_alter_pessoas_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoas',
            name='cpf',
            field=models.CharField(default='11111111111', max_length=11),
        ),
    ]
