# Generated by Django 4.1.3 on 2022-11-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ficha_cem', '0009_pessoas_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoas',
            name='efetivo',
            field=models.BooleanField(choices=[('S', True), ('N', False)], default=False, verbose_name='Efetivo: '),
        ),
    ]
