# Generated by Django 4.1.3 on 2022-11-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ficha_cem', '0011_cargos_pessoas_dt_nasc_alter_pessoas_efetivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoas',
            name='admissao',
            field=models.DateField(default='1991-01-01', verbose_name='Data de Admissão: '),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='cpf',
            field=models.CharField(default='11111111111', max_length=11, verbose_name='CPF: '),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='dt_nasc',
            field=models.DateField(default='1991-01-01', verbose_name='Data de Nascimento: '),
        ),
    ]
