# Generated by Django 4.1.3 on 2022-12-09 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_falta', '0001_initial'),
        ('app_ficha_cem', '0016_alter_pessoas_cargo_delete_cargos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faltas_pessoas',
            name='falta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_falta.faltas'),
        ),
        migrations.DeleteModel(
            name='Faltas',
        ),
    ]
