# Generated by Django 4.1.3 on 2022-12-09 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ficha_cem', '0017_alter_faltas_pessoas_falta_delete_faltas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoas',
            name='cargo',
        ),
    ]
