# Generated by Django 4.1.3 on 2022-12-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ficha_cem', '0019_alter_faltas_pessoas_pessoa_alter_pontuacoes_pessoa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontuacoes',
            name='cargo_atrib',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='pontuacoes',
            name='funcao_atrib',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='pontuacoes',
            name='ue_atrib',
            field=models.CharField(default=0, max_length=5),
        ),
    ]
