# Generated by Django 4.1.3 on 2022-12-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pessoa', '0006_alter_pessoas_saida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoas',
            name='saida',
            field=models.DateField(null=True),
        ),
    ]
