# Generated by Django 5.1.6 on 2025-02-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pessoa', '0007_alter_pessoas_saida'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoas',
            name='ativo',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True),
        ),
    ]
