# Generated by Django 5.1.6 on 2025-07-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_pessoa", "0008_pessoas_ativo"),
    ]

    operations = [
        migrations.AddField(
            model_name="pessoas",
            name="func_publico",
            field=models.BooleanField(
                choices=[(True, "Sim"), (False, "Não")], default=True
            ),
        ),
    ]
