# Generated by Django 5.2.10 on 2026-08-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ColetaMetricasBancoSQL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_hora", models.DateTimeField(auto_now_add=True)),
                ("operacao", models.CharField(max_length=100)),
                ("sql", models.TextField()),
                ("tempo_execucao_ms", models.FloatField()),
                ("banco", models.CharField(blank=True, max_length=100, null=True)),
                ("tabela", models.CharField(blank=True, max_length=100, null=True)),
                ("sucesso", models.BooleanField(default=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["data_hora"], name="monitoramen_data_ho_33df60_idx"
                    ),
                    models.Index(
                        fields=["operacao"], name="monitoramen_operaca_23ceaf_idx"
                    ),
                ],
            },
        ),
    ]
