# Generated by Django 5.2.10 on 2026-08-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoramento", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coletametricasbancosql",
            name="endpoint",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="coletametricasbancosql",
            name="metodo",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
