# Generated by Django 5.2.10 on 2026-08-25 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitoramento", "0002_coletametricasbancosql_endpoint_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coletametricasbancosql",
            name="tabela",
        ),
    ]
