# Generated by Django 4.2.3 on 2024-02-02 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appClasse', '0002_alter_classe_unique_together'),
        ('appAluno', '0009_delete_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='aluno',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='appAluno.aluno'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='ano',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matricula',
            name='classe',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='appClasse.classe'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='numero',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matricula',
            name='situacao',
            field=models.CharField(choices=[('C', 'CURSANDO'), ('T', 'TRANSFERIDO'), ('P', 'PROMOVIDO'), ('R', 'REPROVADO')], default='', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together={('ano', 'aluno', 'situacao')},
        ),
    ]
