# Generated by Django 4.2.3 on 2024-02-02 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAluno', '0012_alter_matricula_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='periodo',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='serie',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='turma',
        ),
    ]
