# Generated by Django 4.2.3 on 2024-02-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAluno', '0017_matricula_data_matricula_matricula_data_movimentacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='data_matricula',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='data_movimentacao',
            field=models.DateField(default=0),
        ),
    ]
