# Generated by Django 4.2.3 on 2024-02-09 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAluno', '0021_alter_matricula_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together={('ano', 'aluno', 'situacao', 'data_matricula')},
        ),
    ]
