# Generated by Django 4.2.3 on 2024-03-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAluno', '0022_alter_matricula_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='situacao',
            field=models.CharField(choices=[('C', 'CURSANDO'), ('BXTR', 'TRANSFERIDO'), ('REMA', 'REMANEJADO'), ('NFP', 'Ñ COMP. FORA PRAZO'), ('P', 'PROMOVIDO'), ('R', 'REPROVADO'), ('A', 'ARQUIVADA')], default='A', max_length=4),
        ),
    ]
