# Generated by Django 4.2.3 on 2024-03-05 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAluno', '0023_alter_matricula_situacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Matricula',
        ),
    ]
