# Generated by Django 5.1.6 on 2025-12-21 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                ("rm", models.IntegerField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=150)),
                ("status", models.IntegerField(default=0)),
                ("ra", models.CharField(default="", max_length=100)),
                ("d_ra", models.CharField(default="", max_length=1)),
                ("data_nascimento", models.CharField(default="", max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Ano",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano", models.IntegerField(unique=True)),
                ("fechado", models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Prontuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        choices=[
                            ("CN", "Certidão de Nascimento"),
                            ("RGA", "RG - Aluno"),
                            ("CPFA", "CPF - Aluno"),
                            ("CV", "Carteira Vacinação"),
                            ("RGR", "RG - Responsável"),
                            ("CPFR", "CPF - Responsável"),
                            ("CNH", "CNH"),
                            ("FM", "Ficha de Matrícula"),
                            ("CR", "Comprovante de Residência"),
                            ("LD", "Laudo"),
                            ("OT", "Outros"),
                        ],
                        default="",
                        max_length=4,
                    ),
                ),
                ("caminho", models.ImageField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Classe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serie", models.CharField(max_length=1)),
                ("turma", models.CharField(max_length=1)),
                (
                    "periodo",
                    models.CharField(
                        choices=[("M", "MANHÃ"), ("T", "TARDE"), ("I", "INTEGRAL")],
                        max_length=1,
                    ),
                ),
                (
                    "ano",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="aluno.ano"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Matricula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.IntegerField(default=0)),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("C", "CURSANDO"),
                            ("BXTR", "TRANSFERIDO"),
                            ("REMA", "REMANEJADO"),
                            ("NCFP", "Ñ COMP. FORA PRAZO"),
                            ("P", "PROMOVIDO"),
                            ("R", "REPROVADO"),
                        ],
                        default="A",
                        max_length=4,
                    ),
                ),
                ("data_matricula", models.DateField(null=True)),
                ("data_movimentacao", models.DateField(null=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="aluno.aluno",
                    ),
                ),
                (
                    "ano",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="aluno.ano",
                    ),
                ),
                (
                    "classe",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="aluno.classe",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Telefone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contato",
                    models.CharField(
                        choices=[
                            ("M", "MÃE"),
                            ("P", "PAI"),
                            ("T", "TIA/TIO"),
                            ("I", "IRMÃ/IRMÃO"),
                            ("A", "AVÓ/AVÔ"),
                            ("R", "RESPONSÁVEL"),
                            ("O", "OUTRO"),
                        ],
                        max_length=1,
                    ),
                ),
                ("numero", models.CharField(default="", max_length=10)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="aluno.aluno"
                    ),
                ),
            ],
        ),
    ]
