# Generated by Django 5.1.6 on 2025-12-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aluno", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="data_nascimento",
            field=models.DateField(blank=True, null=True),
        ),
    ]
