# Generated by Django 5.2.10 on 2026-08-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aluno", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aluno",
            name="cor",
            field=models.IntegerField(
                choices=[
                    (0, "Branco"),
                    (1, "Preto"),
                    (2, "Pardo"),
                    (3, "Amarelo"),
                    (4, "Indígena"),
                    (5, "Não Declarado"),
                ],
                default=5,
            ),
        ),
    ]
