# Generated by Django 5.2.10 on 2026-08-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aluno", "0002_aluno_cor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="cor",
            field=models.IntegerField(
                choices=[
                    (0, "Branco"),
                    (1, "Preto"),
                    (2, "Pardo"),
                    (3, "Amarelo"),
                    (4, "Indígena"),
                    (5, "Outros"),
                ],
                default=5,
            ),
        ),
    ]
