# Generated by Django 5.1.6 on 2025-12-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aluno", "0002_alter_aluno_data_nascimento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="d_ra",
            field=models.CharField(blank=True, default="", max_length=1, null=True),
        ),
    ]
