# Generated by Django 5.1.6 on 2025-12-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aluno", "0003_alter_aluno_d_ra"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Arquivado"), (1, "Cancelado"), (2, "Ativo")],
                db_default=0,
                default=2,
            ),
        ),
    ]
