# Generated by Django 5.1.6 on 2026-01-10 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aluno", "0004_alter_aluno_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matricula",
            name="classe",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="matriculas",
                to="aluno.classe",
            ),
        ),
        migrations.AlterField(
            model_name="telefone",
            name="aluno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="telefones",
                to="aluno.aluno",
            ),
        ),
        migrations.AlterField(
            model_name="telefone",
            name="numero",
            field=models.CharField(default="", max_length=11),
        ),
        migrations.AlterUniqueTogether(
            name="matricula",
            unique_together={
                ("ano", "aluno", "situacao", "data_matricula", "data_movimentacao")
            },
        ),
    ]
