# Generated by Django 5.1.6 on 2026-01-10 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aluno", "0005_alter_matricula_classe_alter_telefone_aluno_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matricula",
            name="classe",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.RESTRICT,
                to="aluno.classe",
            ),
        ),
    ]
