# Generated by Django 5.1.6 on 2026-01-10 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aluno", "0006_alter_matricula_classe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matricula",
            name="aluno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="matriculas",
                to="aluno.aluno",
            ),
        ),
        migrations.AlterField(
            model_name="matricula",
            name="ano",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="aluno.ano"
            ),
        ),
        migrations.AlterField(
            model_name="matricula",
            name="classe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="matriculas",
                to="aluno.classe",
            ),
        ),
        migrations.AlterField(
            model_name="matricula",
            name="data_matricula",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="matricula",
            name="data_movimentacao",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="matricula",
            name="situacao",
            field=models.CharField(
                choices=[
                    ("C", "CURSANDO"),
                    ("BXTR", "TRANSFERIDO"),
                    ("REMA", "REMANEJADO"),
                    ("NCFP", "Ñ COMP. FORA PRAZO"),
                    ("P", "PROMOVIDO"),
                    ("R", "REPROVADO"),
                ],
                default="C",
                max_length=4,
            ),
        ),
        migrations.AddIndex(
            model_name="matricula",
            index=models.Index(
                fields=["aluno", "-ano"], name="aluno_matri_aluno_i_bb6a79_idx"
            ),
        ),
    ]
