# Generated by Django 5.1.6 on 2026-01-20 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aluno", "0007_alter_matricula_aluno_alter_matricula_ano_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Arquivado"), (1, "Cancelado"), (2, "Ativo")], default=0
            ),
        ),
    ]
