# Generated by Django 4.2.3 on 2024-03-06 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAluno', '0024_delete_matricula'),
        ('appMatricula', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together={('ano', 'aluno', 'situacao', 'data_movimentacao')},
        ),
    ]
