# Generated by Django 4.2.3 on 2024-03-25 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAluno', '0024_delete_matricula'),
        ('appMatricula', '0003_alter_matricula_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together={('ano', 'aluno', 'situacao', 'data_matricula', 'data_movimentacao')},
        ),
    ]
