# Generated by Django 4.1.3 on 2022-11-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ficha_cem', '0003_alter_faltas_pessoas_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='faltas_pessoas',
            name='qtd_dias',
            field=models.IntegerField(default=1),
        ),
    ]
