# Generated by Django 4.1.3 on 2022-11-14 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ficha_cem', '0004_faltas_pessoas_qtd_dias'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoas',
            name='admissao',
            field=models.DateField(default='1991-01-01'),
        ),
    ]
