# Generated by Django 4.1.3 on 2022-11-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ficha_cem', '0012_alter_pessoas_admissao_alter_pessoas_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoas',
            name='admissao',
            field=models.DateField(default='1991-01-01'),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='cpf',
            field=models.CharField(default='11111111111', max_length=11),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='dt_nasc',
            field=models.DateField(default='1991-01-01'),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='efetivo',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False),
        ),
    ]
