# Generated by Django 4.1.3 on 2022-11-25 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_ficha_cem', '0013_alter_pessoas_admissao_alter_pessoas_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoas',
            name='cargo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_ficha_cem.cargos'),
        ),
    ]
