# Generated by Django 4.1.3 on 2022-11-30 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_ficha_cem', '0014_pessoas_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoas',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ficha_cem.cargos'),
        ),
    ]
