# Generated by Django 4.1.3 on 2022-12-11 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ficha_cem', '0020_pontuacoes_cargo_atrib_pontuacoes_funcao_atrib_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PontuacoesAtribuicoes',
        ),
    ]
