# Generated by Django 4.1.3 on 2022-12-12 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ficha_cem', '0021_delete_pontuacoesatribuicoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontuacoes',
            name='ano',
            field=models.IntegerField(),
        ),
      
        migrations.AlterField(
            model_name='pontuacoes',
            name='cargo_atrib',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pontuacoes',
            name='funcao',
            field=models.IntegerField(),
        ),
          migrations.AlterField(
            model_name='pontuacoes',
            name='cargo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pontuacoes',
            name='funcao_atrib',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pontuacoes',
            name='ue',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pontuacoes',
            name='ue_atrib',
            field=models.IntegerField(),
        ),
    ]
