# Generated by Django 4.1.3 on 2022-12-15 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ficha_cem', '0022_alter_pontuacoes_ano_alter_pontuacoes_cargo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontuacoes',
            name='cargo_atrib',
        ),
        migrations.RemoveField(
            model_name='pontuacoes',
            name='funcao_atrib',
        ),
        migrations.RemoveField(
            model_name='pontuacoes',
            name='ue_atrib',
        ),
    ]
