# Generated by Django 5.1.6 on 2025-07-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_cargo", "0001_initial"),
        ("app_falta", "0001_initial"),
        ("app_ficha_cem", "0023_remove_pontuacoes_cargo_atrib_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FiltroSalvo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                (
                    "efetivo",
                    models.CharField(
                        choices=[("ambos", "Ambos"), ("sim", "Sim"), ("nao", "Não")],
                        max_length=10,
                    ),
                ),
                (
                    "ativo",
                    models.CharField(
                        choices=[("ambos", "Ambos"), ("sim", "Sim"), ("nao", "Não")],
                        max_length=10,
                    ),
                ),
                ("cargos", models.ManyToManyField(blank=True, to="app_cargo.cargos")),
                ("faltas", models.ManyToManyField(blank=True, to="app_falta.faltas")),
            ],
        ),
    ]
