# Generated by Django 5.1.6 on 2025-12-19 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_ficha_cem", "0024_filtrosalvo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Pontuacoes",
        ),
    ]
