# Generated by Django 4.2.3 on 2024-01-19 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAluno', '0008_alter_telefone_numero'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Classe',
        ),
    ]
