# Generated by Django 4.2.3 on 2024-02-02 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAluno', '0011_alter_matricula_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
