# Generated by Django 4.2.3 on 2024-02-06 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAluno', '0013_remove_aluno_ano_remove_aluno_periodo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='cancelado',
            new_name='status',
        ),
    ]
