# Generated by Django 4.2.3 on 2024-02-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAluno', '0014_rename_cancelado_aluno_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
