# Generated by Django 4.2.3 on 2024-02-07 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAluno', '0015_alter_aluno_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='rm',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
