# Generated by Django 5.1.6 on 2025-12-19 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_pessoa", "0009_pessoas_func_publico"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pontuacoes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano", models.IntegerField()),
                ("funcao", models.IntegerField()),
                ("cargo", models.IntegerField()),
                ("ue", models.IntegerField()),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_pessoa.pessoas",
                    ),
                ),
            ],
            options={
                "unique_together": {("ano", "pessoa")},
            },
        ),
    ]
