# Generated by Django 4.2.3 on 2024-05-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAluno', '0024_delete_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='status',
            field=models.IntegerField(),
        ),
    ]
