# Generated by Django 4.2.3 on 2024-10-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAluno', '0025_alter_aluno_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
