# Generated by Django 4.2.3 on 2024-01-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(default='', max_length=1)),
                ('turma', models.CharField(default='', max_length=1)),
                ('ano', models.CharField(default='', max_length=4)),
                ('periodo', models.CharField(choices=[('M', 'MANHÃ'), ('T', 'TARDE')], default='', max_length=1)),
            ],
        ),
    ]
