# Generated by Django 4.2.3 on 2024-10-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appClasse', '0003_alter_classe_ano_alter_classe_periodo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='periodo',
            field=models.CharField(choices=[('M', 'MANHÃ'), ('T', 'TARDE'), ('I', 'INTEGRAL')], max_length=1),
        ),
    ]
